# Generated by Django 3.0.7 on 2020-06-08 02:15

import SkyCryptoClub.API.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('largeName', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minTip', models.DecimalField(decimal_places=8, default=0, max_digits=21)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Currency')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Platform')),
            ],
            options={
                'unique_together': {('platform', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='PublicityBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
                ('imageType', models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='large', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(default=SkyCryptoClub.API.models.Role.setId, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=35)),
                ('color', models.CharField(default='#a8a8a8', max_length=7)),
                ('isDefault', models.BooleanField(default=False)),
                ('adminPanel', models.BooleanField(default=False)),
                ('adminStatistics', models.BooleanField(default=False)),
                ('editMemberships', models.BooleanField(default=False)),
                ('createMemberships', models.BooleanField(default=False)),
                ('deleteMemberships', models.BooleanField(default=False)),
                ('addPlatform', models.BooleanField(default=False)),
                ('editPlatform', models.BooleanField(default=False)),
                ('deletePlatform', models.BooleanField(default=False)),
                ('banUser', models.BooleanField(default=False)),
                ('permanentBan', models.BooleanField(default=False)),
                ('editXP', models.BooleanField(default=False)),
                ('editUserMembership', models.BooleanField(default=False)),
                ('addCurrency', models.BooleanField(default=False)),
                ('editCurrency', models.BooleanField(default=False)),
                ('deleteCurrency', models.BooleanField(default=False)),
                ('addBorrowStatus', models.BooleanField(default=False)),
                ('editBorrowStatus', models.BooleanField(default=False)),
                ('removeBorrowStatus', models.BooleanField(default=False)),
                ('editBorrow', models.BooleanField(default=False)),
                ('addExchangeStatus', models.BooleanField(default=False)),
                ('editExchangeStatus', models.BooleanField(default=False)),
                ('removeExchangeStatus', models.BooleanField(default=False)),
                ('editExchange', models.BooleanField(default=False)),
                ('addFAQCategory', models.BooleanField(default=False)),
                ('editFAQCategory', models.BooleanField(default=False)),
                ('removeFAQCategory', models.BooleanField(default=False)),
                ('approveFAQ', models.BooleanField(default=False)),
                ('addAccount', models.BooleanField(default=False)),
                ('editAccount', models.BooleanField(default=False)),
                ('createRole', models.BooleanField(default=False)),
                ('editRole', models.BooleanField(default=False)),
                ('removeRole', models.BooleanField(default=False)),
                ('assignRole', models.BooleanField(default=False)),
                ('moderationPanel', models.BooleanField(default=False)),
                ('banExchange', models.BooleanField(default=False)),
                ('banBorrow', models.BooleanField(default=False)),
                ('banLend', models.BooleanField(default=False)),
                ('closeExchange', models.BooleanField(default=False)),
                ('closeBorrow', models.BooleanField(default=False)),
                ('viewTickets', models.BooleanField(default=False)),
                ('respondTickets', models.BooleanField(default=False)),
                ('closeTickets', models.BooleanField(default=False)),
                ('addFAQ', models.BooleanField(default=False)),
                ('editFAQ', models.BooleanField(default=False)),
                ('removeFAQ', models.BooleanField(default=False)),
                ('viewUserBorrows', models.BooleanField(default=False)),
                ('viewUserLendings', models.BooleanField(default=False)),
                ('viewUserProfile', models.BooleanField(default=False)),
                ('viewUserExchanges', models.BooleanField(default=False)),
                ('viewExchange', models.BooleanField(default=False)),
                ('viewBorrow', models.BooleanField(default=False)),
                ('viewUserBalance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='default_avatar.jpg', upload_to=SkyCryptoClub.API.models.avatar_upload)),
                ('xp', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('level', models.BigIntegerField(default=0)),
                ('publicStats', models.BooleanField(default=True)),
                ('publicLevel', models.BooleanField(default=True)),
                ('publicXP', models.BooleanField(default=True)),
                ('publicName', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('publicId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=35, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoFactorLogin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default=SkyCryptoClub.API.models.TwoFactorLogin.setKey, max_length=35)),
                ('valid_until', models.DateTimeField(default=SkyCryptoClub.API.models.TwoFactorLogin.setValid)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='API.FAQCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default=SkyCryptoClub.API.models.PasswordToken.setKey, max_length=35)),
                ('valid_until', models.DateTimeField(default=SkyCryptoClub.API.models.PasswordToken.setValid)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=35)),
                ('active', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Platform')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Profile')),
            ],
            options={
                'unique_together': {('profile', 'platform', 'username')},
            },
        ),
        migrations.CreateModel(
            name='ProfileBan',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.Profile')),
                ('totalBan', models.BooleanField(default=False)),
                ('exchangeBan', models.BooleanField(default=False)),
                ('borrowBan', models.BooleanField(default=False)),
                ('lendBan', models.BooleanField(default=False)),
                ('withdrawBan', models.BooleanField(default=False)),
                ('banDue', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='API.Profile')),
                ('totalExchangesStarted', models.BigIntegerField(default=0)),
                ('totalExchangesSent', models.BigIntegerField(default=0)),
                ('numberBTCSent', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('amountBTCSent', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('numberBTCReceived', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('amountBTCReceived', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('numberETHSent', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('amountETHSent', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('numberETHReceived', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('amountETHReceived', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('numberLTCSent', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('amountLTCSent', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('numberLTCReceived', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('amountLTCReceived', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('numberXDGSent', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('amountXDGSent', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('numberXDGReceived', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('amountXDGReceived', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('numberBCHSent', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('amountBCHSent', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('numberBCHReceived', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('amountBCHReceived', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('numberXRPSent', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('amountXRPSent', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('numberXRPReceived', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('amountXRPReceived', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('numberTRXSent', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('amountTRXSent', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('numberTRXReceived', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('amountTRXReceived', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('to_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='API.PlatformCurrency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency', to='API.PlatformCurrency')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to='API.Profile')),
                ('exchanged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanger_user', to='API.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.PlatformCurrency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Profile')),
            ],
            options={
                'unique_together': {('profile', 'store')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Role')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Profile')),
            ],
            options={
                'unique_together': {('profile', 'primary'), ('profile', 'role')},
            },
        ),
        migrations.CreateModel(
            name='FoundDeposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipId', models.CharField(max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Account')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Platform')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Profile')),
            ],
            options={
                'unique_together': {('tipId', 'account', 'platform')},
            },
        ),
    ]
