# Generated by Django 3.0.8 on 2020-07-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileban',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Profile'),
        ),
    ]
