# Generated by Django 3.0.5 on 2020-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_squashed_0040_platformcurrency_mintip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcurrency',
            name='minTip',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=21),
        ),
    ]
