# Generated by Django 3.0.8 on 2020-07-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('clicks', models.BigIntegerField(default=0)),
                ('registrations', models.BigIntegerField(default=0)),
                ('limit', models.BigIntegerField(default=-1)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.Profile')),
            ],
        ),
    ]
