# Generated by Django 3.0.6 on 2020-05-11 04:56

import SkyCryptoClub.API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200428_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to=SkyCryptoClub.API.models.avatar_upload),
        ),
    ]
