# Generated by Django 3.0.8 on 2020-07-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200708_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='unban',
            field=models.BooleanField(default=False),
        ),
    ]
