# Generated by Django 3.0.7 on 2020-06-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200608_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='id',
            new_name='eid',
        ),
    ]
