# Generated by Django 3.0.8 on 2020-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_founddeposit_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
