# Generated by Django 3.0.8 on 2020-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_faqcategory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBan',
            fields=[
                ('ipAddress', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('permanent', models.BooleanField(default=False)),
            ],
        ),
    ]
