# Generated by Django 3.0.6 on 2020-05-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200511_0456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('profile', 'role'), ('profile', 'primary')},
        ),
    ]
