# Generated by Django 3.0.7 on 2020-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200608_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
