# Generated by Django 3.0.8 on 2020-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200707_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twofactor',
            field=models.BooleanField(default=True),
        ),
    ]
