# Generated by Django 3.0.6 on 2020-05-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200511_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='primary',
            field=models.BooleanField(default=True),
        ),
    ]
