# Generated by Django 3.0.7 on 2020-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_currency_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='ratio',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
