# Generated by Django 3.0.6 on 2020-05-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200511_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicityBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/')),
                ('imageType', models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='large', max_length=35)),
            ],
        ),
    ]
