# Generated by Django 3.0.7 on 2020-06-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_exchange_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeStatus',
            fields=[
                ('status', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.ExchangeStatus'),
        ),
    ]
