# Generated by Django 3.0.8 on 2020-07-21 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_announcement_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='Message')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global Notification',
                'verbose_name_plural': 'Global Notifications',
            },
        ),
        migrations.RemoveField(
            model_name='readannouncement',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='readannouncement',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='ReadAnnouncement',
        ),
    ]
