# Generated by Django 3.0.7 on 2020-06-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200612_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangestatus',
            name='color',
            field=models.CharField(default='#a8a8a8', max_length=7),
        ),
    ]
