# Generated by Django 3.0.7 on 2020-06-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_exchangestatus_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAmount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('maxamount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='creator_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchanger_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='exchange',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.ExchangeTax'),
        ),
    ]
