# Generated by Django 3.0.7 on 2020-06-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200612_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTaxPeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minAmount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('maxamount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='tax',
        ),
        migrations.DeleteModel(
            name='ExchangeTax',
        ),
        migrations.AddField(
            model_name='exchange',
            name='taxCreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_tax', to='API.ExchangeTaxPeer'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='taxExchanger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanger_tax', to='API.ExchangeTaxPeer'),
        ),
    ]
