# Generated by Django 3.0.7 on 2020-06-12 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200612_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
