# Generated by Django 3.0.7 on 2020-06-14 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20200613_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('name', models.CharField(max_length=35, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticketId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=60)),
                ('status', models.CharField(default='Open', max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.SupportCategory')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Message')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Profile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.SupportTicket')),
            ],
        ),
    ]
