# Generated by Django 3.0.7 on 2020-06-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_supportcategory_supportticket_supportticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='status',
        ),
    ]
