# Generated by Django 3.0.7 on 2020-06-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_remove_supportticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcategory',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
