# Generated by Django 3.0.7 on 2020-06-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_supportcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='last_replied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_replier', to='API.Profile'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='API.Profile'),
        ),
    ]
