# Generated by Django 3.0.7 on 2020-06-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_auto_20200614_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
