# Generated by Django 3.0.8 on 2020-07-19 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('title', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('released', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('featureType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChangeLog.FeatureType')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChangeLog.Update')),
            ],
        ),
    ]
